experiment_name: worldmodel

data:
  symbols:
    - 'BTCUSDT'
    - 'ETHUSDT'
    - 'SOLUSDT'
    - 'XRPUSDT'
    - 'HYPEUSDT'
    - 'SUIUSDT'
    - 'BNBUSDT'
    - 'ZECUSDT'
    - 'LINKUSDT'
    - 'AAVEUSDT'
    - 'WLDUSDT'
    - 'ONDOUSDT'
    - 'XLMUSDT'
  timeframe: '1m'
  sequence_length: 64
  stride: 32
  window_size: 15
  num_bins: 61
  extreme_value: 0.03
  sigma: 0.2
  normalization_window: 1440
  training_interval: 
    - '2018-01-01 00:00'
    - '2025-01-01 00:00'
  validation_interval:
    - '2025-01-01 00:00'
    - '2026-01-01 00:00'
  test_interval:
    - '2026-01-01 00:00'
    - '2026-06-01 00:00'

jepa:
  name: 'jepa-v1'
  input_dim: 6 # [Open, High, Low, Close, Volume, Volatility]
  d_model: 128
  encoder:
    num_layers: 16
    num_heads: 4
    max_len: 16
    dropout: 0.1
  predictor:
    num_layers: 32
    num_heads: 8
    max_len: 64
    num_bins: 61
    dropout: 0.1
  lam_SIGReg: 0.1
  lam_CE: 1.0
  lr: 0.0003
  training:
    epochs: 1000
    batch_size: 128
    log_every_n_steps: 10

actorcritic:
  name: 'autotrader-v1'
  action_bins: 201
  num_layers: 16
  num_heads: 8
  max_len: 64
  dropout: 0.1
  start_temperature: 1.4
  min_temperature: 0.4
  lr: 0.0003
  gamma: 0.99 # Diskounteringsfaktor
  gae_lambda: 0.95 # Generalized Advantage Estimation
  ppo_clip: 0.2 # PPO clipping interval (epsilon)
  ent_coef: 0.01 # Entropi-vægt (sikrer udforskning)
  vf_coef: 0.5 # Critic loss vægt
  ppo_epochs: 4 # Hvor mange gange vi genbruger drømme-data
  dream_horizon: 15 # Hvor langt frem vi drømmer
  commission_value: 0.0005
  training:
    epochs: 1000
    batch_size: 8
    log_every_n_steps: 10

