experiment_name: worldmodel

data:
  symbols:
     - 'BTCUSDT'
     - 'ETHUSDT'
     - 'SOLUSDT'
     - 'XRPUSDT'
     - 'HYPEUSDT'
     - 'SUIUSDT'
     - 'BNBUSDT'
     - 'ZECUSDT'
     - 'LINKUSDT'
     - 'AAVEUSDT'
     - 'WLDUSDT'
     - 'ONDOUSDT'
     - 'XLMUSDT'
  timeframe: '1m'
  normalization_window: 1440
  window_size: 15
  sequence_length: 64
  stride: 32
  returns:
    num_bins: 61
    min_value: -0.03
    max_value: 0.03
  actions:
    num_bins: 51
    min_value: -1.0
    max_value: 1.0
    commission_value: 0.0005
  training_interval: 
    - '2018-01-01 00:00'
    - '2025-01-01 00:00'
  validation_interval:
    - '2025-01-01 00:00'
    - '2026-01-01 00:00'
  test_interval:
    - '2026-01-01 00:00'
    - '2026-06-01 00:00'

jepa:
  name: 'jepa-actor'
  input_dim: 6 # [Open, High, Low, Close, Volume, Volatility]
  d_model: 64
  encoder:
    num_layers: 24
    num_heads: 8
    max_len: ${eval:'${data.window_size} + 1'}
    dropout: 0.1
  predictor:
    num_layers: 48
    num_heads: 16
    max_len: ${data.sequence_length}
    dropout: 0.1
  return_head:
    num_bins: ${data.returns.num_bins}
    min_value: ${data.returns.min_value}
    max_value: ${data.returns.max_value}
    dropout: 0.1
  action_head:
    num_bins: ${data.actions.num_bins}
    min_value: ${data.actions.min_value}
    max_value: ${data.actions.max_value}
    dropout: 0.1
  training:
    lr: 0.0003
    warmup: 100
    epochs: 2000
    batch_size: 200
    log_every_n_steps: 10
  ar_training:
    lr: 0.0003
    horizon: 5
    action_temperature: 1.0
    commission_value: ${data.actions.commission_value}
    warmup: 100
    epochs: 500
    batch_size: 100

