experiment_name: worldmodel

data:
  symbols:
    - 'BTCUSDT'
    - 'ETHUSDT'
    - 'SOLUSDT'
    - 'XRPUSDT'
    #- 'HYPEUSDT'
    #- 'SUIUSDT'
    #- 'BNBUSDT'
    #- 'ZECUSDT'
    #- 'LINKUSDT'
    #- 'AAVEUSDT'
    #- 'WLDUSDT'
    #- 'ONDOUSDT'
    #- 'XLMUSDT'
  timeframe: '1m'
  sequence_length: 64
  stride: 32
  window_size: 15
  num_bins: 256
  extreme_value: 0.15
  sigma: 0.8
  normalization_window: 200
  training_interval: 
    - '2018-01-01 00:00'
    - '2025-01-01 00:00'
  validation_interval:
    - '2025-01-01 00:00'
    - '2026-01-01 00:00'
  test_interval:
    - '2026-01-01 00:00'
    - '2026-06-01 00:00'

jepa:
    input_dim: 6 # [Open, High, Low, Close, Volume, Volatility]
    d_model: 2048
    encoder:
      num_layers: 6
      num_heads: 4
      max_len: 16
      dropout: 0.1
    predictor:
      num_layers: 12
      num_heads: 4
      max_len: 64
      num_bins: 256
      dropout: 0.1
    lam_SIGReg: 0.1
    lam_KLD: 0.05
    lr: 0.001
    training:
      epochs: 100
      batch_size: 16
      log_every_n_steps: 10

